Peekmo/atom-autocomplete-php

php/providers/ClassMapRefresh.php
php/providers/ClassesProvider.php
php/services/Tools.php

Properly escape all arguments passed to exec(), and also invoke composer using the php binary.
This allows the package to work on Windows, even with paths containing spaces.

Fixes php subcommand invocations.

---

php/ErrorHandler.php
php/parser.php

Properly handles all errors, and avoid outputting non-JSON text whatever is configured in php.ini.

Catch any error and exception and display them in JSON.

---

lib/goto/function-goto.coffee
lib/providers/autocomplete-provider.coffee
lib/services/php-file-parser.coffee
php/providers/AutocompleteProvider.php
php/services/Tools.php

Couple of fixes to bugs I found while using.
1. Multi line function calls didn't work with the go to functionality.
2. If a property and a method is named the same the property would overwrite the method. Now both are suggested.
3. If your class or namespace declarations weren't all lowercase it wouldn't autocomplete.
I found that chained functions `$this->index()->search()` ..etc will go to as well, as long as the function has a `@return`.

Fixes to multi line goto and others

---

lib/goto/abstract-goto.coffee
lib/goto/class-goto.coffee
lib/goto/function-goto.coffee
lib/goto/goto-manager.coffee
lib/goto/property-goto.coffee
lib/services/php-file-parser.coffee
php/providers/AutocompleteProvider.php
php/services/Tools.php

* Added property goto. Works very similar to how functions works (almost the exact same code)
* Added a notification if the function goto isn't able to jump because proxy.methods returns an error.
* Found this when trying to jump to an Eloquent function in Laravel.
* Fixed if the goto class is in the same namespace as the currently opened class
* Fixed the namespace and class selectors for alt-click not always working.
* Re-enabled the class goto. (From testing I couldn't replicate any problems)
* Fixed getStackClasses not working with things like 
```
$test = parent::foo()
---
```
```
$test->foo(function($test) {
return $test;
})->filter()
------
```
* Did some updates to findFullWord function as I needed to define between a property and a function using `(`
* Fixed if the phpdoc has a …

Bugfixes + property goto

---

lib/goto/abstract-goto.coffee
lib/goto/class-goto.coffee
lib/goto/function-goto.coffee
lib/goto/property-goto.coffee
php/services/Tools.php

Hello
I decided to start tinkering a bit with the code myself, annoying you with pull requests as well as bug reports ;-). This adds support for mouse tooltips when hovering over known methods and properties.
Note the following things:
* The current timeout for the tooltip is 500ms, which seems reasonable to avoid annoying the user.
* Tooltips on class names are not implemented as I'm not sure docblocks from classes are even extracted on the PHP side at the moment. I've added a TODO in class-goto for this.
* Very strangely, I've noticed that sometimes it takes a few mousemove and mouseout events for the tooltip to start showing for the first time, even though the code is actually properly executed. After the initial show, it works as intended for that specific `HTMLElement`.
@CWDN  I've …

Add tooltips with descriptions on mouse hover.

---

php/services/Tools.php

Hello
This adds three dots to the last parameter of variadic functions/methods, the most common example of this are many of the the built-in array functions, such as `array_map`. By adding the three dots, it is clear that after the last parameter can be repeated as many times as necessary, without creating an extra argument in autocompletion when tabbing through the argument list.

For variadic methods, add three dots to the last parameter.

---

lib/services/php-file-parser.coffee

Hello
This fixes an issue where `parseStackClass` did not prune comments before attempting to process the text. See also [1] for an example where you couldn't alt-click on the methods because these lines were not filtered out.
[1] https://github.com/hotoiledgoblinsack/php-autocomplete-test/blob/cae052ad03b39b912ed4788cb795321349f62dd7/src/TestNamespace/SomeClass.php#L283

Prune comments in parseStackClass before processing (fixes issue with fluent methods and alt-click).

---

lib/goto/abstract-goto.coffee
lib/goto/function-goto.coffee
lib/goto/property-goto.coffee
php/services/DocParser.php
php/services/Tools.php

Hello
This improvement fetches the thrown (@throws) exceptions listed in the docblock and displays them in the tooltip, along with a description of when they are thrown (if it is present in the docblock).
This also improves the formatting of the tooltip a bit, ensuring it is always left-aligned rather than centered, bolding the method/property name, etc.

Fetch thrown exceptions for methods and show them in the tooltip.

---

lib/config.coffee
lib/goto/function-goto.coffee
lib/providers/autocomplete-provider.coffee
lib/providers/function-provider.coffee
php/providers/StaticsProvider.php
php/services/DocParser.php
php/services/Tools.php

Hello
This further improves on your implementation of #34 by using the docblock from the method or property in parent classes if available, which is mostly useful for overrides so you don't have to copy the docblock over to get the description.

Let method and property docblocks inherit from parent classes and refactor.

---

lib/config.coffee
lib/peekmo-php-atom-autocomplete.coffee

Hello
This works towards a solution for issue #30 and tests that PHP and Composer can be called. If not, the package shows an error and just completely stops doing anything else. This will hopefully also cut back on the (confusing) errors and bug reports originating from incorrect setups.
Hope this helps and any feedback is of course welcome.

Test the configuration before going through with initialization.

---

lib/goto/abstract-goto.coffee
lib/goto/function-goto.coffee
lib/goto/property-goto.coffee

Hello
This adds some more sanity checks to code I recently submitted and fixes **undefined** showing up as tooltip sometimes. This was happening because the tooltip didn't check if there was actually anything to show (which there isn't for classes because it isn't implemented yet).

Don't show a tooltip when there is none to show and add sanity checks.

---

lib/goto/function-goto.coffee

Hello
This fixes an issue with the method description tooltip where a docblock such as:
```
/**
* Description
*
* @throws \Exception
*/
```
... would cause the tooltip to show `\Exception null` instead of just `\Exception`.

function-goto - Do not add a description of the thrown exception if it is null.

---

lib/services/php-file-parser.coffee

Hello
This further improves on my previous improvements to `parseStackClass` by properly stripping the content inside parantheses if there are nested method or function calls. The regular expression choked on this [1], causing tooltips and alt-clicking to fail.
[1] https://github.com/hotoiledgoblinsack/php-autocomplete-test/blob/943446f06ea58c61b3a09ad689d8ff5d1bb35ffa/src/TestNamespace/SomeClass.php#L311

parseStackClass - Fixed not properly handling nested method and function calls.

---

lib/goto/abstract-goto.coffee
lib/goto/class-goto.coffee
lib/goto/function-goto.coffee
lib/peekmo-php-atom-autocomplete.coffee
php/services/Tools.php
styles/peekmo-php-atom-autocomplete.less

Hello
This adds basic support for annotating overrides of methods for classes as well as interface implementations (both in a different color). The annotations are added to the default gutter when the markers are registered (at the same time as the goto markers). I've also let the annotations as well as the goto markers be reset and rescanned when a file is saved.
On the PHP side, I also provided `isImplementationOf` and `isOverrideOf`, as I thought it would be really nice to be able to have tooltips on the annotation or be able to click through to the respective class (we already have the information anyway), but I haven't been able to figure out how to do this yet and figured that even in its current state, this is already useful and we can always add it later.
Hopefully this will be a …

Add annotations for method overrides and interface implementations. 

---

lib/goto/function-goto.coffee
styles/peekmo-php-atom-autocomplete.less

Hello
In pull request #87 I added support for annotations and noted that I wanted to make them clickable and give them tooltips. Well... now I have ;-). With this pull request you can hover over the annotation in the gutter to see what the annotation actually means and which class or interface the method you're overriding/implementing originates from. You can then click the annotation to navigate to the method in that class or interface. 
This also fixes a bug where ```cleanMarkers``` made ```annotationMarkers``` completely empty for all files, instead of just for the current file.

Enhancement - Clickable annotations with tooltips.

---

lib/services/php-file-parser.coffee

Hello
This removes the previous workaround I had to apply in `isInFunction` because of a bug in the language-php package [1]. They have now resolved that bug in Atom v1.0.12 (language-php 0.30.0), which causes our workaround to actually become a bug, as each closure will be counted as two scope opens.
[1] https://github.com/atom/language-php/issues/98 .

Bugfix - Remove now obsolete bugfix in isInFunction for Atom 1.0.12.

---

lib/goto/abstract-goto.coffee
lib/goto/function-goto.coffee
php/services/Tools.php

Hello
It turns out that in Atom v1.0.12, the class names used by the default gutter have changed, causing event handlers on annotations to no longer be registered. It seems they now just give a `.line-number` class to each line and no longer a `.line-number-X` (with X the number of the row), which wasn't documented in the official release notes. 
Apart from that, this also replaces the use of `jumpWord` and `jumpLine` in places where the line was already known beforehand. Atom now supports jumping to a specific line by specifying the `initialLine` option, which removes the need for our manual jumping after a specific timeout. Sadly this can't replace all our uses, as some of them rely on scanning the file based on a regex after opening it. Because of this I only refactored out `jumpLine` …

Bugfix / Refactoring - Fix annotation event handlers no longer working in Atom 1.0.12.

---

lib/providers/self-provider.coffee

Hello
The `static` keyword can be used to apply late static binding of static methods, which the `self` keyword does not apply. If I understand correctly (correct me if I'm wrong ;-), as the child class can be anything from the perspective of the class using the `static` keyword, it should probably be treated the same as the `self` keyword.

Bugfix - Also handle static:: in self-provider.

---

lib/providers/autocomplete-provider.coffee
lib/providers/self-provider.coffee
lib/providers/static-provider.coffee
php/providers/StaticsProvider.php
php/services/Tools.php

Hello
This fixes a couple of issues I noticed, mostly with completion of static properties and constants:
* `self-provider` and `static-provider` assumed that when an entry was not a record, it must be a constant, it could however also be a (static) property, which should have a different style class in autocomplete-plus.
* `StaticsProvider::execute` duplicated a lot of code from `Tools::getClassMetadata` and was outdated, the former now uses the latter directly.
* Constant fetching was added to `Tools::getClassMetadata`, resulting constants to also be listed for `$this->`. This may seem strange, but e.g. `$this->MY_CONSTANT` is correct PHP code (I however wouldn't advise using it ;-).

Bugfix - Fix several issues with constants and static properties.

---

lib/goto/abstract-goto.coffee

Hello
This adds line breaks to the method tooltip in the same places as there was a newline. This ensures that if you have a multiline summary of (long) description in your docblock, the tooltip will have the lines broken at the same locations as the original docblock. This also fixes the issue where the tooltips could get incredibly wide.

Bugfix - Replace newlines with line breaks for the tooltip.

---

lib/services/php-file-parser.coffee

Hello
I had some files where I couldn't alt-click some methods that should have been working correctly which I also couldn't reproduce in an isolated environment. Then it turned out this was the culprit:
```
<?php
/**
* Blah class.
*
* ...
*/
namespace X;
use ...
```
Because `findUseForClass` exits early when it finds the word `class`, it was stumbling over the docblock at the top of the file and not scanning any of the use statements. This corrects that by checking if the location the word was found is a comment.

Bugfix - Fixed findUseForClass not skipping comments when exiting early.

---

lib/goto/function-goto.coffee
php/services/DocParser.php
php/services/Tools.php

Hello
This pull request contains the following changes:
* The method tooltip now uses `div`s instead of `span`s. This resolves the issue where only the first line of the description and summary would have a margin when it spanned multiple lines.
* The method tooltip now shows the parameters and return type of a method (without their description, for now).
* The long description will now no longer trim out extra newlines that you added in the docblock for clarity.
* The summary and long description will no longer filter out any asterisks or slashes inside the string itself.
* `DocParser` will now differentiate between no docblock or a docblock without a `@return` tag. This is because, according to the phpDocumentor documentation, a docblock without a return tag implies `@return void`, …

Enhancement - Improve method tooltips.

---

php/Config.php
php/ErrorHandler.php
php/parser.php
php/providers/AutocompleteProvider.php
php/providers/AutoloadClassMap.php
php/providers/ClassMapRefresh.php
php/providers/ClassProvider.php
php/providers/ClassesProvider.php
php/providers/DocParamProvider.php
php/providers/FunctionsProvider.php
php/providers/MethodsProvider.php
php/providers/ParentProvider.php
php/providers/ProviderInterface.php
php/providers/StaticsProvider.php
php/services/DocParser.php
php/services/FileParser.php
php/services/Tools.php

Exemple : In Prestashop, we have a "Tools" class without namespace. There's a "Tools" class in this package, Reflection is done on the wrong source class.

[Proposal] Add a namespace to all PHP classes to avoid Reflection conflicts

---

php/services/FileParser.php

Hello
`getCompleteNamespace` in `FileParser` was being too greedy and also matching use statements that ended in the class searched for. For example:
```
namespace SomeNamespace;
use \MyMailer;
class Mailer
{
/**
* @return Mailer
*/
public function foo()
{
// ...
}
}
```
Here, when alt-clicking the `foo` method for an instance of Mailer, `AutocompleteProvider` would return `MyMailer` because it analyzes the end of the use statement, ignoring whether it is only part of the name or the complete name. This adds a simple check that assumes if the part matched is not preceded by a backslash or a space, then it is not the entire name.
Hope this helps.

Bugfix - Fixed getCompleteNamespace being too greedy.

---

php/providers/AutocompleteProvider.php

Hello
This fixes `self` being treated the same way as `$this` and `static` when autocompleting, while it is actually the same as mentioning the class name explicitly, for example:
```
class A
{
/**
* @return A
*/
public function foo1() {}
/**
* @return self
*/
public function foo2() {}
/**
* @return self
*/
public function foo3() {}
}
class B extends A
{
/**
* @return self
*/
public function foo3() {}
}
$b = new B();
$b->foo1(); // Returns instance of A, as indicated by docblock.
$b->foo2(); // Returns instance of A, as self refers to the name of the class declaring the method.
$b->foo3(); // Returns instance of B, as the method and its docblock was overriden in the child class and self now refers to B.
```
`static` or `$this` can be used in these cases to let `foo2` resolve to `B` …

Bugfix - Fixed self being treated the same way as $this and static.

---

lib/goto/abstract-goto.coffee
lib/goto/function-goto.coffee
lib/goto/property-goto.coffee
lib/services/php-file-parser.coffee

Hello
This started as a solution for mixing static method access followed by non-static method access causing tooltips and go-to to fail. For example:
```
Foo::bar()->someMethod();
```
No tooltips would show up for `someMethod` nor would go-to work properly. As a side effect this also seems to fix alt-clicking and tooltips on methods invoked using `self` and `static`.
When going through the code to fix these issues, I ran into some oddities and things that seemed to be performed without reason, such as spltting the term by `->` or `::` and then popping the last element off. It turns out these were only needed when performing go-to with the keyboard, so I moved these to be performed only for the keyboard go-to, which allowed to simplify a lot of the code.
If you notice anything that I …

Bugfix - Fix tooltips and go-to failing when mixing static and contextual method access.

---

php/services/Tools.php

Hello
As mentioned in ticket #86, some large frameworks such as Symfony use inheritDoc incorrectly. Because it would be a major convenience for those using these frameworks, I added a leniency to the docblock parsing that pretends no docblock is present when it only consists of the single `{@inheritDoc}` or `{@inheritdoc}`.

Tools - Ticket #86 - Support (incorrect) use of inheritDoc.

---

lib/services/php-file-parser.coffee
php/providers/AutocompleteProvider.php
php/services/FileParser.php

Hello
This fixes an issue where class names in docblocks such as `Foo\Bar`, if they were relative, would not be detected correctly. This was because `getCompleteNamespace` assumed that if a class name contained multiple slashes, it must be absolute. It turned out this was a little more tricky to fix than it seemed at first sight as there are the following cases:
* `\Foo\Bar` is always absolute, nothing needs to be done here.
* `Foo\Bar` could refer to `\Foo\Bar` if composer.json is configured as such.
* `Foo\Bar` could refer to e.g. `My\Foo\Bar` if the current namespace is `My`.
This pull request does the following things to `AutocompleteProvider::execute`:
* I think (please correct me if I'm wrong) that `FileParser` should not be opened on the class the method is requested in. Instead it …

Bugfix - Fixed relative class names in docblocks not being treated entirely correctly.

---

lib/goto/class-provider.coffee
lib/tooltip/abstract-provider.coffee
lib/tooltip/function-provider.coffee
lib/tooltip/property-provider.coffee
styles/peekmo-php-atom-autocomplete.less

Hello
Seeing as it turns out I've been abusing Atom's tooltips and there is no actual popover implementation available in Atom (yet), I've replaced them with a custom simple popover.
I really didn't want to have to create a custom implementation for this, but it seems, for the moment, we have little choice (that is at least if we want to see these issues resolved). Note the following things:
* The popover does not try to intelligently place itself somewhere in the editor. It just puts the arrow in the center of the word and is displayed about 12.5% of the width of the tooltip. Very very wide popovers may very well fall off the screen. Popovers will also not position themselves above the word if there is no space at the bottom (but I believe that currently doesn't happen either with our …

Bugfix - Create a custom tooltip popover.

---

php/providers/AutocompleteProvider.php

Hello
It turned out that, with my last pull request fixing imports, I broke imports by use statement (the one thing I didn't test, the irony ;-) due to simply having forgotten to handle the 'else' clause (i.e. when `useStatementFound` was true).
I also did some minor refactoring, improving clarity and making sure the provider always returns data, does not fetch the same class twice if unnecessary and loosening the restriction of the class having to be available in the class map. The latter I did because, as far as I can see, all the code here can cope with classes that aren't in the Composer classmap; if there is an unsupported file, it will simply silently fail, but in many cases it could still work, providing autocompletion for those classes as well. However, if this is something you …

Bugfix - Fix imports by use statements no longer working due to my refactoring.

---

lib/tooltip/abstract-provider.coffee

Hello
As described in #132, I'm creating this pull request even though it's not really necessary anymore. However, since I broke it I should probably also fix it properly (as punishment ;-). 
(Also, you never know if, in the future, the z-index of the tree view for some reason would become lower than that of the text editor, causing the tooltip to catch input there.)

Bugfix - Properly hide and show tooltips again.

---

php/services/FileParser.php

Hello
Today I'm bringing you more fixes and refactoring to the `FileParser`. This does the following:
* Also let the search for a namespace and use statements stop on the `trait` and `interface` keyword (minor optimization).
* Compare segments of the use statements and class name after an `explode`, this removes the 'hack' I previously added to work around `use \My_Test` being detected as a use statement for `Test` because it matched partially.
* A bugfix for using class names relative to an import, e.g. `use A\B\C;` and then `@return C\D`.
* A bugfix for the corner case where you had class names relative to an aliased import, e.g. `use A\B\C as D;` and then `@return D\E`.
* Thanks to gradually refactoring the code, I noticed that the code for both aliased imports and non-aliased imports …

Bugfix - FileParser and full class retrieval (also contains refactoring).

---

lib/providers/function-provider.coffee

Hello
This lifts the `functionOnly` restriction on the function provider, allowing autocompletion of built-in PHP functions everywhere (they do not have any namespace or class dependencies anyway).
The modification to the regex is to also allow the start of the line as a valid prefix, otherwise a line without indentation will not trigger the autocompletion.

Enhancement - Also allow function-provider to work outside functions.

---

lib/tooltip/abstract-provider.coffee

Hello
This hopefully resolves ticket #140. I've also had it happen a few times, but can't reliably reproduce it and don't know why it is happening. IIRC it recently appeared, but the `screenPositionForMouseEvent` was also used before the tooltip refactoring.

Tooltip - Hopefully fix issue #140.

---

lib/goto/abstract-provider.coffee
lib/goto/class-provider.coffee

Hello
The selector returned for class alt-click request all namespace and class children of the parent when a match is found, which is a little bit too greedy. Take the following example:
```php
$something->test('someString', function ($var) {
return new TestNamespace\Foo\FooClass(new Bar\BarTrait());
--------------------------     -------------
<Mouse>
});
```
When I hover over the first class, the second class also gets underlined, and, by consequence, the class goto fails. This was resolved by just returning the element hovered over and the previous and next elements that are part of it, not all the children matching the same selector.

Bugfix - Fixed the class provider alt-click selector being too greedy.

---

php/providers/ClassMapRefresh.php
php/providers/DocParamProvider.php
php/services/FileParser.php

Hello
This modifies `ClassMapRefresh` to only force a class map refresh when doing the full index. After that, it can just use `getCompleteNamespace` to retrieve the class in the modified file. This implements #118 and hopefully will make incremental indexing after the initial index much faster for large projects, as the bottleneck seems to be the composer class dump there.

Enhancement - Skip a Composer class dump on incremental save.

---

lib/goto/function-provider.coffee
lib/goto/property-provider.coffee
php/providers/AutocompleteProvider.php
php/services/Tools.php

Hello
This refactors the `Tools` class again, fixing several issues and improving several things:
* Use of the autoload class map has been made redundant in several parts of the code due to being able to fetch the filename through reflection. This removes the need to perform an extra PHP call in several locations. Go to seems to be a tad smoother now.
* Determining the full class path based on use statements and the namespace in a file happened using the `declaringClass`, which was wrong if the method or property was actually located in a trait (in another file).
* Go to and clicking annotations of members originating from traits now works properly, navigating to the member in the trait itself.
* Fixes #98, #138 and #145.
On the technical side, there is now `declaringClass` and …

Bugfix - Refactor the indexing Tools, fixing several issues.

---

lib/providers/abstract-provider.coffee
lib/providers/autocomplete-provider.coffee
lib/providers/class-provider.coffee
lib/providers/function-provider.coffee
lib/providers/parent-provider.coffee
lib/providers/self-provider.coffee
lib/providers/static-provider.coffee
lib/providers/variable-provider.coffee
lib/services/php-file-parser.coffee

Hello
This pull request contains the following improvements:
* Autocompletion for variables now works outside of functions as well. This is useful for e.g. `require`-d files that still contain use statements or use absolute class paths.
* Refactored `getVariableType`.
* `getVariableType` will no longer assume `/** @var FooType $var */` is actually a `/** @var FooType */` that applies to the variable below it if the variable below it. (Before, it always assumed that it needed to override it, even if the variable below it was is not `$var`.)
* `getVariableType` now supports PHPStorm's `/** @var Footype $var */` (and it also still supports IntelliJ's `/** @var $var FooType */`).
* The longer type overrides that contain the name of the variable can now be anywhere in the function and will …

Enhancement - Allow autocompletion outside functions and improve support for type override annotations.

---

php/providers/AutocompleteProvider.php
php/services/DocParser.php

Hello
This implements #153 and will cause the `AutocompleteProvider` to ignore basic types. This way you can have a docblock with `@return FooClass|null` and still get autocompletion for `FooClass`. As discussed, only simple types are pruned and if there are multiple class types, no autocompletion is provided as before.

Enhancement - When autocompleting after a member with multiple return types, ignore basic types.

---

lib/providers/member-provider.coffee

Hello
This fixes an issue with the member-provider regex where it could no longer cope with autocompletion over multiple lines, which is often used with the fluent interface (see also `testChaining` in my test repository).

Bugfix - member-provider is no longer able to cope with multiple lines.

---

lib/providers/member-provider.coffee

Hello
It appears the changes from pull request #160 got lost. I think this happened because I originally had these changes in pull request #159, but I reverted them there so I could split them off into a separate pull request because it didn't belong there. You merged #160 first and then #159 later, which probably caused the commit to get applied from #160, then applied again in #159 (which caused no changes) and then reverted by #159 (I cherry picked the change, causing it to use the same commit hash).

Bugfix - Reapply a pull request that got lost.

---

lib/goto/function-provider.coffee
lib/services/attached-popover.coffee
lib/services/popover.coffee
lib/tooltip/abstract-provider.coffee
styles/peekmo-php-atom-autocomplete.less

Hello
This splits off the popover code used in the tooltip providers into two separate classes: `Popover` and `AttachedPopover`.
* `Popover`: can have text set and will show or hide itself by calling its methods at specified X and Y coordinates.
* `AttachedPopover`: same as `Popover`, but attaches itself to a specific element, displaying itself at its location.
The new code is now also used in the `function-provider` for the annotation popovers, so they display immediately. This fixes #156.

Bugfix - Ticket #156 - Refactor popover into two separate classes and fix annotation tooltips.

---

lib/providers/abstract-provider.coffee
lib/providers/class-provider.coffee
lib/providers/function-provider.coffee
lib/providers/member-provider.coffee

Hello
This implements #136 and will stop the providers for functions, methods and constructors from inserting the parameter list when one is already present. Only the character index right after the insertion point will be checked, so your cursor must be right before the opening parenthesis for this to be prevented. In all other cases, the full parameter list will be inserted. Regardless of what happens, the autocompletion suggestion will still show the entire signature for clarity.
Hopefully this will increase usability for everyone (I know it will for me, at least ;-).

Enhancement - Ticket #136 - Don't insert a parameter list when one is already present.

---

lib/goto/class-provider.coffee
lib/services/php-file-parser.coffee
lib/tooltip/abstract-provider.coffee
lib/tooltip/class-provider.coffee
lib/tooltip/tooltip-manager.coffee
php/services/Tools.php

Hello
This implements ticket #121. Classes, interfaces and traits will now have tooltips showing their documentation. The tooltip shows the class name, the full class name, the summary and the long description (if it is available).
As a nice side effect, use statements that point to a class, trait or interface will also have tooltips.

Enhancement - Ticket #121 - Implement tooltips for classes.

---

lib/goto/function-provider.coffee
lib/tooltip/abstract-provider.coffee

Hello
This fixes the sticky popovers mentioned in pull request #174. This also fixes the same problem for the annotation popovers. Furthermore, the 'stickyness' that popovers seem to have always had is now gone as they are removed when the view scrolls.
The problem was that when Atom scrolls an element out of the view, the element is removed from the DOM and the mouseout event is never sent anymore, leaving the popover in a frozen state on the screen.

Bugfix - Fix sticky popovers.

---

lib/services/php-file-parser.coffee

Hello
This fixes #178, where closures were not examined for type hints when fetching the type of local variables. Next to that, the regex was updated as it was generating problems if the first type hint was a FQCN prefixed by a slash (in that case it could not determine the type of the variable from the first parameter type hint correctly).
I also fixed an issue where the line text kept getting larger and larger because all the text in the range from the line to the cursor position was fetched. This probably never caused any problems because the regexes (regices?) were matching the first part of the string anyway and the other parts of the string, that were wrongly included, were already checked for the same regex. The fix should also improve performance a bit because there is less text …

Bugfix - Ticket #178 - Fixed closures not being scanned for type hints.

---

lib/annotation/abstract-provider.coffee
lib/annotation/annotation-manager.coffee
lib/annotation/method-provider.coffee
lib/goto/abstract-provider.coffee
lib/goto/function-provider.coffee
lib/peekmo-php-atom-autocomplete.coffee
lib/tooltip/abstract-provider.coffee

Hello
This refactors annotations into separate providers (because they really did not belong in the go to providers) and fixes #155. I've also fixed some additional issues with popovers freezing when one was being shown while the editor closed or the element attached to was removed while it was open.

Bugfix/Refactoring - Split off annotations and fix more pesky tooltips.

---

lib/autocompletion/class-provider.coffee
lib/config.coffee
lib/peekmo-php-atom-autocomplete.coffee
lib/services/php-file-parser.coffee

Hello
This implements a  'smarter' `addUseClass` that will not just place the use statements under the last use statement, but will try to find the existing use statement that it thinks it fits the most and place the new use statement there. Together with a new configuration option (disabled by default to not annoy anyone) which you can use to also allow inserting newlines, this will hopefully result in much cleaner lists of use statements.
The reason for this is that most implementations usually aren't very smart when it comes to use statements. After a while of coding, the result is something like this:
```php
use A\B\C\D\E;
use A\B;
use MoreCodeHere\SomeNamespace\SomeLongerName;
use B\F\A;
use MyFoo\Bar\Something;
...
```
With these changes and the newline option enabled, the package …

Enhancement - Implement a smarter addUseClass.

---

lib/annotation/abstract-provider.coffee
lib/annotation/annotation-manager.coffee
lib/annotation/method-provider.coffee
lib/annotation/property-provider.coffee
lib/goto/function-provider.coffee
lib/goto/property-provider.coffee
lib/services/php-file-parser.coffee
lib/tooltip/function-provider.coffee
lib/tooltip/property-provider.coffee
php/services/Tools.php

Hello
This pull request:
* Adds annotations for class properties.
* Reduces code duplication by merging `getMethodContext` and `getPropertyContext` into one, as they already were mostly the same method.
* Refactors the annotation provider so the new property provider can reuse most of the code from the existing method provider.

Enhancement - Ticket #144 - Add annotations for properties.

---

lib/services/php-file-parser.coffee

Hello
This fixes #196 where the use statement would awkwardly squeeze itself in between existing groups when it contained one of the existing use statements in its own namespace.

Bugfix - Ticket #196 - Fix awkward placement of use statements when containing one of the existing use statements in its own name.

---

lib/autocompletion/class-provider.coffee
lib/autocompletion/member-provider.coffee
lib/services/popover.coffee
lib/tooltip/function-provider.coffee
lib/tooltip/property-provider.coffee
php/providers/AutocompleteProvider.php
php/providers/ClassMapRefresh.php
php/providers/ClassProvider.php
php/services/DocParser.php
php/services/Tools.php
styles/peekmo-php-atom-autocomplete.less

Hello
This contains the following changes:
* Refactor `DocParser` to make the code more flexible and allows (more easily) dealing with tags that may contain newlines in their descriptions.
* Put a maximum width on the documentation popover, as with very very large descriptions it was filling most of the screen.
* Don't replace newlines from the original docblock with line breaks. Documentation text should be treated much like HTML: newlines don't actually mean a line break but are merely used when writing the docblock itself. However, when there are two consecutive newlines present, it is clear that the user wants to create a 'section'. In that case, two line breaks are inserted to logically separate the text.
* Popovers still had an ID assigned, which wasn't used and is also invalid if …

Enhancement - Ticket #120 - Show descriptions for the return type and parameters. 

---

lib/annotation/abstract-provider.coffee

Hi @Peekmo.
For performance reasons, we needed to drop the `maintainHistory` option when creating individual markers in Atom 1.3. This was a breaking change, but this package was the only user I found.
You can still maintain history on markers, but you now have to create them in their own "marker layer", which groups together related markers, and history is maintained on the entire layer. It's easier for us to save the state of the marker index in the undo history when we aren't mixing historied and unhistoried markers.
Anyway, running this package seems pretty complicated for a non-PHP user like me, so you'll definitely need to test my changes against Atom 1.2 and Atom 1.3, which comes out in beta soon. But this is the approach needed to keep the history tracking on your markers. Please …

Use marker layers if available to support maintainHistory markers

---

lib/goto/class-provider.coffee

The issue with using alt + click on class names still occurred due to classesResponse not being unless and yet not having the autocomplete property. This fixes it.

Uncaught TypeError: Cannot read property 'length' of undefined Fix #61

---

php/ErrorHandler.php

register_shutdown_function, set_error_handler and register_shutdown_function require fully qualified class name.

Fixed error handling.

---

lib/services/php-file-parser.coffee
php/Config.php
php/providers/ClassProvider.php
php/providers/ConstantsProvider.php
php/providers/DocParamProvider.php
php/providers/FunctionsProvider.php
php/services/FileParser.php
php/services/Tools.php

As described in #250, the package is not able to autocomplete local variables where the first character of the namespace is a lowercase character. E.g.:
```
$bar = new \foo\Bar;
```
This pull request fixes that issue.

Fix autocompletion for namespace with leading lowercase character - fixes #250

---

php/ErrorHandler.php
php/services/DocParser.php

Currently `php/ErrorHandler.php` sets `display_errors` and `log_errors` to false, which is fine. However it suppresses the PHP warnings  that the subsequent `set_error_handler` etc. calls fail since 03046a1 introduced a namespace on the class.
This pull request calls these function with the FQCN now as needed.
Besides the second commit fixes two uses of undefined variables which were well hidden due to that as well.

Fix error handling

---

php/services/DocParser.php

--Change DocParser::parse parameter $methodName to $itemName
Fixes #258

Fix DocParser parameter name

---

php/services/DocParser.php
php/services/Tools.php

Added class dockblock parsing for only @property and @method.
For example CakePHP3, some model table instances are set dynamically as property of controller class.
Now autocomplete and tooltip of this package does not work like this.
```php
class ArticlesController extends AppController
{
public function index()
{
$this->Articles->find();
}
}
```
So I added parsing docblock like this.
```php
/**
* @property \App\Model\Table\ArticlesTable $Articles
* @method string getParentName()
*/
class ArticlesController extends AppController
```

Added class docblock parsing for @property and @method

---

keymaps/atom-autocomplete-php.cson
lib/autocompletion/class-provider.coffee
lib/config.coffee
lib/services/use-statement.coffee
lib/views/class-list-view.coffee

This commit adds a new "Import Use Statement" command that can be triggered any time. It uses as much of the existing autocompletion code as possible, but fetches suggestions for the word under the cursor.

Add ability to import use statement outside of autocompletion

---

lib/annotation/abstract-provider.coffee
lib/tooltip/abstract-provider.coffee

This fixes two errors on attempting to deactivate the package:
* The Tooltip provider had a leftover code fragment from an older incarnation that attempted to remove a non-existent element from `document`.
* The Annotation provider called out to `removeAnnotations` with no editor passed in in its `deactivate`, but this wasn't handled in that function.
Fixes #312.

Fix errors on package deactivation
